name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: |
          sudo apt-get install sshpass
          
      - name: Test SSH connection
        run: |
          sshpass -p '12345678' ssh -v deploy@147.93.112.162 "echo 'SSH connection successful'"

      - name: Copy files to VM
        run: |
          scp -r . ${{ secrets.SSH_USER }}@${{ secrets.VM_IP }}:/path/to/deploy

      - name: Run setup script on VM
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_IP }} "cd /path/to/deploy && chmod +x setup.sh && ./setup.sh"
