name: Setup VPS SSH Access

on:
  workflow_dispatch:  # Manually trigger this workflow from GitHub Actions

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Generate SSH Key
        run: |
          ssh-keygen -t rsa -b 4096 -f id_rsa -N ""
          echo "PRIVATE_KEY<<EOF" >> $GITHUB_ENV
          cat id_rsa >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "PUBLIC_KEY=$(cat id_rsa.pub)" >> $GITHUB_ENV

      - name: Add Public Key to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
          mkdir -p ~/.ssh
          echo "${{ env.PUBLIC_KEY }}" >> ~/.ssh/authorized_keys
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/authorized_keys
          EOF

      - name: Store Private Key as GitHub Secret (Manual Step)
        run: |
          echo "Go to GitHub Repository -> Settings -> Secrets and Variables -> Actions"
          echo "Create a new secret named VPS_SSH_KEY and paste the following private key:"
          echo "${{ env.PRIVATE_KEY }}"
