name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: generate key
        run: |
          ssh-keygen -t ed25519 -C "Amitshendge1990@gmail.com" -N "" -f ~/.ssh/id_ed25519 <<< y > /dev/null && cat ~/.ssh/id_ed25519.pub
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Debug SSH key
        run: |
          echo "Private key:"
          cat ~/.ssh/id_rsa
          echo "Public key:"
          ssh-keygen -y -f ~/.ssh/id_rsa

      - name: Test SSH connection
        run: |
          ssh -v ${{ secrets.SSH_USER }}@${{ secrets.VM_IP }} "echo 'SSH connection successful'"

      - name: Copy files to VM
        run: |
          scp -r . ${{ secrets.SSH_USER }}@${{ secrets.VM_IP }}:/path/to/deploy

      - name: Run setup script on VM
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.VM_IP }} "cd /path/to/deploy && chmod +x setup.sh && ./setup.sh"
